version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "ewallet_db"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
    ports:
      - "5432:5432"